language: node_js
node_js:
  - 12
script:
  - npm run test
notifications:  
  email:  
    recipients:  
    - ufrapl21@gmail.com
    - jeffrey.mblanc@gmail.com
    on_success: always  
    on_failure: always